/*
 * Copyright (C) 2015 Adrián Ledo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package presentacion;

import clases.Contacto;
import clases.Grupo;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adrian Ledo
 */
public class VentanaGrupos extends javax.swing.JInternalFrame
{
    private VentanaPrincipal principal;
    private DefaultListModel<Grupo> mdlGrupos;
    private DefaultListModel<Contacto> mdlContactosGrupo;
    private DefaultComboBoxModel<Contacto> mdlContactosUsuario;
    
    VentanaGrupos(VentanaPrincipal principal) {
        initComponents();
        this.principal = principal;
        this.mdlGrupos = new DefaultListModel<>();
        this.mdlContactosGrupo = new DefaultListModel<>();
        this.mdlContactosUsuario = new DefaultComboBoxModel<>();
        this.lstGrupos.setModel(this.mdlGrupos);
        this.lstContactos.setModel(mdlContactosGrupo);
        this.cmbContactosUsuario.setModel(mdlContactosUsuario);
        this.principal.actualizarGrupos();
        this.principal.actualizarContactos();
        this.limpiarCampos();
        
        java.net.URL helpURL = this.getClass().getResource("/ayudas/ayuda.hs");
        try {
            HelpSet helpset = new HelpSet(null, helpURL);
            HelpBroker broker = helpset.createHelpBroker();
            broker.enableHelpKey(this, "pagGrupos", helpset);
        } catch (HelpSetException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnuAbrirVContactos = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGrupos = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstContactos = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        cmbContactosUsuario = new javax.swing.JComboBox();
        btnAnhadirContacto = new javax.swing.JButton();
        btnExpulsarContacto = new javax.swing.JButton();

        mnuAbrirVContactos.setText("Abrir ventana Contactos");
        mnuAbrirVContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirVContactosActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnuAbrirVContactos);

        setClosable(true);
        setResizable(true);
        setTitle("Grupos");
        setPreferredSize(new java.awt.Dimension(350, 300));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        txtNombre.setText("jTextField1");
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(txtNombre, gridBagConstraints);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(btnGuardar, gridBagConstraints);

        lstGrupos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstGrupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstGruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstGrupos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        lstContactos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstContactos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstContactosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstContactos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(jScrollPane2, gridBagConstraints);

        jLabel2.setText("Grupos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Contactos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 10, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        getContentPane().add(btnEliminar, gridBagConstraints);

        cmbContactosUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(cmbContactosUsuario, gridBagConstraints);

        btnAnhadirContacto.setText("Añadir");
        btnAnhadirContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnhadirContactoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(btnAnhadirContacto, gridBagConstraints);

        btnExpulsarContacto.setText("Expulsar Contacto");
        btnExpulsarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpulsarContactoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 2.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(btnExpulsarContacto, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
    GestorVentanas.setGruposAbierta(false);
}//GEN-LAST:event_formInternalFrameClosed

private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    if(this.txtNombre.getText().isEmpty())
    {
        JOptionPane.showMessageDialog(this, "Introduzca un nombre para el grupo");
        return;
    }
    
    if(this.lstGrupos.isSelectionEmpty())
    {
        this.principal.guardarGrupo(new Grupo(this.txtNombre.getText()));
    }
    else
    {
        Grupo g = this.mdlGrupos.getElementAt(this.lstGrupos.getSelectedIndex());
        String nuevoNombre = this.txtNombre.getText();
        this.principal.modificarGrupo(g, nuevoNombre);
    }
}//GEN-LAST:event_btnGuardarActionPerformed

private void lstGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstGruposMouseClicked
    int seleccionado;
    
    if(evt.getClickCount() == 1)
    {
        this.lstGrupos.clearSelection();
        this.limpiarCampos();
        return;
    }
    if((seleccionado=this.lstGrupos.getSelectedIndex()) == -1)
    {
        this.lstGrupos.clearSelection();
        this.limpiarCampos();
        return;
    }
    
    this.principal.mostrarContactosGrupo(this.mdlGrupos.getElementAt(seleccionado));
}//GEN-LAST:event_lstGruposMouseClicked

private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    if(this.lstGrupos.isSelectionEmpty())
    {
        JOptionPane.showMessageDialog(this, "Seleccione un grupo");
        return;
    }
    if((!this.mdlContactosGrupo.isEmpty() && 
            JOptionPane.showConfirmDialog(this, "Existen contactos pertenecientes a este grupo.\n¿Desea eliminarlo igualmente?") == 0)
            || this.mdlContactosGrupo.isEmpty())
    {
        this.principal.eliminarGrupo(this.mdlGrupos.getElementAt(this.lstGrupos.getSelectedIndex()));
    }
    this.limpiarCampos();
}//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAnhadirContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnhadirContactoActionPerformed
        if(this.cmbContactosUsuario.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Seleccione un contacto");
            return;
        }
        if(this.lstGrupos.isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(this, "Seleccione un grupo");
            return;
        }
        Grupo grupo = this.mdlGrupos.elementAt(this.lstGrupos.getSelectedIndex());
        Contacto contacto = this.mdlContactosUsuario.getElementAt(this.cmbContactosUsuario.getSelectedIndex());
        this.principal.insertarGrupoContacto(grupo, contacto);
    }//GEN-LAST:event_btnAnhadirContactoActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            this.btnGuardar.doClick();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void btnExpulsarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpulsarContactoActionPerformed
        if(this.lstContactos.isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(this, "Seleccione un contacto");
            return;
        }
        
        if(this.lstGrupos.isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(this, "Seleccione un grupo");
            return;
        }
        
        Grupo g = this.mdlGrupos.elementAt(this.lstGrupos.getSelectedIndex());
        Contacto c = this.mdlContactosGrupo.elementAt(this.lstContactos.getSelectedIndex());
        this.principal.expulsarContactoDeGrupo(g, c);
    }//GEN-LAST:event_btnExpulsarContactoActionPerformed

    private void lstContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstContactosMouseClicked
        if(evt.getButton() == MouseEvent.BUTTON3)
        {
            this.jPopupMenu1.show(this.lstContactos, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_lstContactosMouseClicked

    private void mnuAbrirVContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAbrirVContactosActionPerformed
        this.principal.abrirVContactos();
        this.jPopupMenu1.setVisible(false);
    }//GEN-LAST:event_mnuAbrirVContactosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnhadirContacto;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnExpulsarContacto;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cmbContactosUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstContactos;
    private javax.swing.JList lstGrupos;
    private javax.swing.JMenuItem mnuAbrirVContactos;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos()
    {
        this.txtNombre.setText(null);
        this.mdlContactosGrupo.clear();
    }

    void actualizarMdlGrupos(ArrayList<Grupo> grupos)
    {
        this.mdlGrupos.clear();
        this.limpiarCampos();
        if(grupos != null && !grupos.isEmpty())
        {
            for(Grupo g : grupos)
            {
                this.mdlGrupos.addElement(g);
            }
        }
        this.lstGrupos.repaint();
    }

    void actualizarMdlContactosGrupo(ArrayList<Contacto> contactos) {
        this.mdlContactosGrupo.clear();
        this.limpiarCampos();
        if(contactos != null && !contactos.isEmpty())
        {
            for(Contacto c : contactos)
            {
                this.mdlContactosGrupo.addElement(c);
            }
        }
        this.lstContactos.repaint();
    }
    
    void actualizarMdlContactosUsuario(ArrayList<Contacto> contactos)
    {
        this.mdlContactosUsuario.removeAllElements();
        this.limpiarCampos();
        if(contactos != null && !contactos.isEmpty())
        {
            for(Contacto c : contactos)
            {
                this.mdlContactosUsuario.addElement(c);
            }
        }
    }
}
