/*
 * Copyright (C) 2015 Adrián Ledo
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package presentacion;

import clases.Contacto;
import clases.EnvioPrivado;
import clases.Grupo;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.help.HelpBroker;
import javax.help.HelpSet;
import javax.help.HelpSetException;
import javax.swing.DefaultComboBoxModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Adrian Ledo
 */
public class VentanaInformes extends javax.swing.JInternalFrame {

    private VentanaPrincipal principal;
    private DefaultComboBoxModel<Grupo> mdlGrupos;
    private DefaultComboBoxModel<Contacto> mdlContactos;
    
//    private static final String imagen = "../imagenes/Desert.jpg";
    private String directorioClasses;
    private String directorioInformes;
    
        
    public VentanaInformes(VentanaPrincipal principal, String dirClasses) {
        initComponents();
        
        this.principal = principal;
        this.directorioClasses = dirClasses;
        this.directorioInformes = directorioClasses.concat("/informes");
        System.out.println(directorioInformes);
//        try
//        {
//            URL urlInformes = this.getClass().getResource("../informes");
//            directorioInformes = urlInformes.toURI().getPath().substring(1);
//            System.out.println(directorioInformes);
//        } catch (URISyntaxException ex) {
//            Logger.getLogger(VentanaInformes.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
        this.mdlGrupos = new DefaultComboBoxModel<>();
        this.cmbGrupos.setModel(mdlGrupos);
        this.principal.actualizarGrupos();
        
        this.mdlContactos = new DefaultComboBoxModel<>();
        this.cmbContactos.setModel(mdlContactos);
        this.principal.actualizarContactos();
        
        java.net.URL helpURL = this.getClass().getResource("/ayudas/ayuda.hs");
        try {
            HelpSet helpset = new HelpSet(null, helpURL);
            HelpBroker broker = helpset.createHelpBroker();
            broker.enableHelpKey(this, "pagInformes", helpset);
        } catch (HelpSetException ex) {
            Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnListaContactos = new javax.swing.JButton();
        btnListaGrupos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbGrupos = new javax.swing.JComboBox();
        btnContactosGrupo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cmbContactos = new javax.swing.JComboBox();
        btnMensajesContacto = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Informes");
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        btnListaContactos.setText("Listado de contactos");
        btnListaContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaContactosActionPerformed(evt);
            }
        });

        btnListaGrupos.setText("Listado de grupos");
        btnListaGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaGruposActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Grupo");

        cmbGrupos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnContactosGrupo.setText("Contactos de este grupo");
        btnContactosGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContactosGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContactosGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbGrupos, 0, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnContactosGrupo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Contacto");

        cmbContactos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnMensajesContacto.setText("Mensajes con este contacto");
        btnMensajesContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMensajesContactoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMensajesContacto, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbContactos, 0, 288, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMensajesContacto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListaContactos, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                    .addComponent(btnListaGrupos, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnListaContactos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListaGrupos)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
    GestorVentanas.setInformesAbierta(false);
}//GEN-LAST:event_formInternalFrameClosed

    private void btnListaContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaContactosActionPerformed
        this.principal.getInformeContactos();
        /*String listaContactos = directorioInformes.concat("/listaContactos.jrxml");
        String listaContactosCompilado = directorioInformes.concat("/listaContactos.jasper");
        String listaContactosRellenada = directorioInformes.concat("/listaContactos.jrprint");
        String listaContactosPdf = directorioInformes.concat("/listaContactos"+getFechaHora()+".pdf");

        try
        {
            JasperCompileManager.compileReportToFile(listaContactos, listaContactosCompilado);

//            HashMap parametros = new HashMap();
//            parametros.put("LOGO", new FileInputStream(imagen));

            Connection conexion = Conexion.getConexion();
//            JasperFillManager.fillReportToFile(listaPiezasCompilado, listaPiezasRellenada, parametros, conexion);
            JasperFillManager.fillReportToFile(listaContactosCompilado, listaContactosRellenada, new HashMap(), conexion);

            JasperExportManager.exportReportToPdfFile(listaContactosRellenada, listaContactosPdf);

            abrirVisorPDF(listaContactosPdf);
        } catch (JRException ex) {
            Logger.getLogger(VentanaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnListaContactosActionPerformed

    private void btnListaGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaGruposActionPerformed
        this.principal.getInformeGrupos();
        /*String listaGrupos = directorioInformes.concat("/listaGrupos.jrxml");
        String listaGruposCompilado = directorioInformes.concat("/listaGrupos.jasper");
        String listaGruposRellenada = directorioInformes.concat("/listaGrupos.jrprint");
        String listaGruposPdf = directorioInformes.concat("/listaGrupos"+getFechaHora()+".pdf");

        try
        {
            JasperCompileManager.compileReportToFile(listaGrupos, listaGruposCompilado);

//            HashMap parametros = new HashMap();
//            parametros.put("LOGO", new FileInputStream(imagen));

            Connection conexion = Conexion.getConexion();
//            JasperFillManager.fillReportToFile(listaPiezasCompilado, listaPiezasRellenada, parametros, conexion);
            JasperFillManager.fillReportToFile(listaGruposCompilado, listaGruposRellenada, new HashMap(), conexion);

            JasperExportManager.exportReportToPdfFile(listaGruposRellenada, listaGruposPdf);

            abrirVisorPDF(listaGruposPdf);
        } catch (JRException ex) {
            Logger.getLogger(VentanaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnListaGruposActionPerformed

    private void btnContactosGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContactosGrupoActionPerformed
        this.principal.getInformeContactosGrupo(this.mdlGrupos.getElementAt(this.cmbGrupos.getSelectedIndex()));
        /*if(this.cmbGrupos.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Seleccione un grupo");
            return;
        }
        
        String listaContactosGrupo = directorioInformes.concat("/listaContactosGrupo.jrxml");
        String listaContactosGrupoCompilado = directorioInformes.concat("/listaContactosGrupo.jasper");
        String listaContactosGrupoRellenada = directorioInformes.concat("/listaContactosGrupo.jrprint");
        String listaContactosGrupoPdf = directorioInformes.concat("/listaContactosGrupo"+getFechaHora()+".pdf");

        try
        {
            JasperCompileManager.compileReportToFile(listaContactosGrupo, listaContactosGrupoCompilado);

            HashMap parametros = new HashMap();
            parametros.put("GRUPO", this.mdlGrupos.getElementAt(this.cmbGrupos.getSelectedIndex()).getId());

            Connection conexion = Conexion.getConexion();
            JasperFillManager.fillReportToFile(listaContactosGrupoCompilado, listaContactosGrupoRellenada, parametros, conexion);
//            JasperFillManager.fillReportToFile(listaContactosGrupoCompilado, listaContactosGrupoRellenada, new HashMap(), conexion);

            JasperExportManager.exportReportToPdfFile(listaContactosGrupoRellenada, listaContactosGrupoPdf);

            abrirVisorPDF(listaContactosGrupoPdf);
        } catch (JRException ex) {
            Logger.getLogger(VentanaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnContactosGrupoActionPerformed

    private void btnMensajesContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMensajesContactoActionPerformed
        this.principal.getInformeMensajesContacto(this.mdlContactos.getElementAt(this.cmbContactos.getSelectedIndex()));
        /*if(this.cmbContactos.getSelectedIndex() == -1)
        {
            JOptionPane.showMessageDialog(this, "Seleccione un contacto");
            return;
        }
        
        String listaMensajesContacto = directorioInformes.concat("/listaMensajesContacto.jrxml");
        String listaMensajeContactoCompilado = directorioInformes.concat("/listaMensajesContacto.jasper");
        String listaMensajeContactoRellenada = directorioInformes.concat("/listaMensajesContacto.jrprint");
        String listaMensajesContactoPdf = directorioInformes.concat("/listaMensajesContacto"+getFechaHora()+".pdf");

        try
        {
            JasperCompileManager.compileReportToFile(listaMensajesContacto, listaMensajeContactoCompilado);

            HashMap parametros = new HashMap();
            Contacto c = this.mdlContactos.getElementAt(this.cmbContactos.getSelectedIndex());
            parametros.put("CREADOR", c.getCreador());
            parametros.put("ALIAS", c.getAlias());
            
            Connection conexion = Conexion.getConexion();
            JasperFillManager.fillReportToFile(listaMensajeContactoCompilado, listaMensajeContactoRellenada, parametros, conexion);
//            JasperFillManager.fillReportToFile(listaContactosGrupoCompilado, listaContactosGrupoRellenada, new HashMap(), conexion);

            JasperExportManager.exportReportToPdfFile(listaMensajeContactoRellenada, listaMensajesContactoPdf);

            abrirVisorPDF(listaMensajesContactoPdf);
        } catch (JRException ex) {
            Logger.getLogger(VentanaInformes.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_btnMensajesContactoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContactosGrupo;
    private javax.swing.JButton btnListaContactos;
    private javax.swing.JButton btnListaGrupos;
    private javax.swing.JButton btnMensajesContacto;
    private javax.swing.JComboBox cmbContactos;
    private javax.swing.JComboBox cmbGrupos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    void cargarGrupos(ArrayList<Grupo> arrayGrupos) {
        this.mdlGrupos.removeAllElements();
        arrayGrupos.stream().forEach((grupo) -> {
            this.mdlGrupos.addElement(grupo);
        });
        this.cmbGrupos.repaint();
        limpiarCampos();
    }
    
    void cargarContactos(ArrayList<Contacto> arrayContactos)
    {
        this.mdlContactos.removeAllElements();
        arrayContactos.stream().forEach((c) -> {
            this.mdlContactos.addElement(c);
        });
        this.cmbContactos.repaint();
        limpiarCampos();
    }

    private void limpiarCampos() {
        this.cmbGrupos.setSelectedIndex(-1);
        this.cmbContactos.setSelectedIndex(-1);
    }
    
    private String getFechaHora()
    {
        Date fecha = new Date();
        return String.valueOf(fecha.getTime());
    }
    
    private void abrirVisorPDF(String archivo) {
        try {
            Runtime.getRuntime().exec("\""+VentanaPrincipal.rutaPDF+"\" \""+archivo+"\"");
        } catch (IOException ex) {
            Logger.getLogger("ERROR AL ABRIR EL LECTOR DE PDF");
        }
    }

    void genInfContactos(ArrayList<Contacto> contactos) {
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(contactos);
        String informeContactos = directorioInformes.concat("/informeContactos.jrxml");
        
        try
        {
            JasperReport jasperCompilado = JasperCompileManager.compileReport(informeContactos);
            JasperPrint jasperRellenado = JasperFillManager.fillReport(jasperCompilado, null, ds);
            JasperViewer.viewReport(jasperRellenado, false);
        }
        catch (JRException e)
        {
            e.printStackTrace();
        }
    }

    void genInfGrupos(ArrayList<Grupo> grupos) {
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(grupos);
        String informeGrupos = directorioInformes.concat("/informeGrupos.jrxml");
        
        try
        {
            JasperReport jasperCompilado = JasperCompileManager.compileReport(informeGrupos);
            JasperPrint jasperRellenado = JasperFillManager.fillReport(jasperCompilado, null, ds);
            JasperViewer.viewReport(jasperRellenado, false);
        }
        catch (JRException e)
        {
            e.printStackTrace();
        }
    }

    void genInfContactosGrupo(ArrayList<Contacto> contactos) {
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(contactos);
        String informeContactos = directorioInformes.concat("/informeContactosGrupo.jrxml");
        
        try
        {
            JasperReport jasperCompilado = JasperCompileManager.compileReport(informeContactos);
            JasperPrint jasperRellenado = JasperFillManager.fillReport(jasperCompilado, null, ds);
            JasperViewer.viewReport(jasperRellenado, false);
        }
        catch (JRException e)
        {
            e.printStackTrace();
        }
    }

    void genInfMensajesContacto(ArrayList<EnvioPrivado> enviosPrivados) {
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(enviosPrivados);
        String informeMensajes = directorioInformes.concat("/informeMensajesContacto.jrxml");
        
        try
        {
            JasperReport jasperCompilado = JasperCompileManager.compileReport(informeMensajes);
            JasperPrint jasperRellenado = JasperFillManager.fillReport(jasperCompilado, null, ds);
            JasperViewer.viewReport(jasperRellenado, false);
        }
        catch (JRException e)
        {
            e.printStackTrace();
        }
    }
}
